// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa9_88j5O1YtMIA4eKZ__b0Z8BjY08Xco',
    appId: '1:875762331979:web:b59663dbe88dd80551f8ce',
    messagingSenderId: '875762331979',
    projectId: 'tsukulog-1285f',
    authDomain: 'tsukulog-1285f.firebaseapp.com',
    storageBucket: 'tsukulog-1285f.firebasestorage.app',
    measurementId: 'G-PBRWRE2E0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-1G_53iDePz_2lGN_b4ih9y_B8H2wMaM',
    appId: '1:875762331979:android:76e47a8385db5ec751f8ce',
    messagingSenderId: '875762331979',
    projectId: 'tsukulog-1285f',
    storageBucket: 'tsukulog-1285f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDebFxjgybvJNQI73RV2ctKr-BM_eLWTKI',
    appId: '1:875762331979:ios:67981190ff379f7751f8ce',
    messagingSenderId: '875762331979',
    projectId: 'tsukulog-1285f',
    storageBucket: 'tsukulog-1285f.firebasestorage.app',
    iosBundleId: 'com.example.tsukulog',
  );

}